# Generated by Django 5.2 on 2026-06-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=255, unique=True, verbose_name='Адрес'),
        ),
    ]
