# Generated by Django 5.2 on 2026-06-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocache', '0002_alter_location_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='queried_at',
            new_name='updated_at',
        ),
    ]
