# Generated by Django 5.2 on 2026-05-18 15:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_rename_first_name_order_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=18, region='RU', verbose_name='Номер телефона'),
        ),
    ]
