# Generated by Django 5.2 on 2026-05-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NPRC', 'Не обработан'), ('ACTD', 'Принят'), ('PRCD', 'Готовится'), ('DLVR', 'Доставляется'), ('DLRD', 'Выполнен')], db_index=True, default='NPRC', max_length=4, verbose_name='Статус'),
        ),
    ]
