# Generated by Django 5.2 on 2026-05-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='Комментарий к заказу'),
        ),
    ]
