# Generated by Django 5.2 on 2026-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_registrated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_way',
            field=models.CharField(blank=True, choices=[('CASH', 'Наличными'), ('ELCT', 'Электронно')], db_index=True, max_length=5, verbose_name='Способ оплаты'),
        ),
    ]
