# Generated by Django 5.2 on 2026-06-29 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
